ndesk version

diff --git a/cai2bids/convert_data_to_BIDS b/cai2bids/convert_data_to_BIDS
--- a/cai2bids/convert_data_to_BIDS
+++ b/cai2bids/convert_data_to_BIDS
@@ -13,37 +13,37 @@ set -e # this command causes the script to exit on error
 ####################################################################################################
 #### Defining pathways
 ####################################################################################################
-rawloc=/QRISdata/Q1240/VALCERT/source
-outpath=/scratch/user/uqkgarn1/VALCERT
-niidir=/scratch/user/uqkgarn1/VALCERT
-logdir=/scratch/user/uqkgarn1/VALCERTLOGS
+rawloc=~/Desktop/neurodesktop-storage/data/source/
+outpath=~/Desktop/neurodesktop-storage/data/
+niidir=~/Desktop/neurodesktop-storage/data/source/
+logdir=~/Desktop/neurodesktop-storage/data/logs/
 ####################################################################################################
 
-####################################################################################################
-#### copy over data from collection to scratch
-###################################################################################################
-subjs=(1)
-ses=(2)
+# ####################################################################################################
+# #### copy over data from collection to scratch
+# ###################################################################################################
+# subjs=(1)
+# ses=(2)
 
-for subj in "${subjs[@]}"; do
+# for subj in "${subjs[@]}"; do
     
-    for sess in "${ses[@]}"; do
-        raw_fName=$(find ${rawloc}/ -name "sub-0${subj}_CS*") # this will obvs change later
-        echo "${raw_fName}"
-        if [ -z "${raw_fName}" ]
-        then 
-            echo "raw files folder not found"
-            exit 1
-        fi
-        echo "${outpath}"
-        if [ -z "${outpath}" ]
-        then 
-            echo "output path not found"
-            exit 1
-        fi
-        rsync -rv "${raw_fName}" "${outpath}"
-    done
-done
+#     for sess in "${ses[@]}"; do
+#         raw_fName=$(find ${rawloc}/ -name "sub-0${subj}_CS*") # this will obvs change later
+#         echo "${raw_fName}"
+#         if [ -z "${raw_fName}" ]
+#         then 
+#             echo "raw files folder not found"
+#             exit 1
+#         fi
+#         echo "${outpath}"
+#         if [ -z "${outpath}" ]
+#         then 
+#             echo "output path not found"
+#             exit 1
+#         fi
+#         rsync -rv "${raw_fName}" "${outpath}"
+#     done
+# done
 
 
 # # ##################################################################################################
@@ -58,21 +58,24 @@ for subj in "${subjs[@]}"; do
     for sess in "${ses[@]}"; do
     echo "Processing subject $subj session $sess"
 
-    ###Create structure
-    mkdir -p "${niidir}/sub-0${subj}/ses-0${sess}/anat"
+    ###Create structure at the same level as the source data
+    mkdir -p ${niidir}sub-0${subj}/ses-0${sess}/anat
 
     ### extract images of interest
     for z in *mp2rage_*_uni-den.zip; do
         # get folder name for subjects dcm data
-        dcm_fName=$(find "${niidir}/" -name "sub-0${subj}_*") 
+        dcm_fName=$(find "${niidir}" -name "sub-0${subj}_*") 
 		echo  "${dcm_fName}"
-        unzip -d "${niidir}/sub-0${subj}/ses-0${sess}/anat" ${dcm_fName}/$z 
+        # unzip to the subject folder that has been created in source
+        unzip -d "${niidir}sub-0${subj}/ses-0${sess}/anat" "${dcm_fName}/${z}" 
     done
 
-    # convert to nii + BIDS
-    ./dcm2niix -o ${niidir}/sub-0${subj}/ses-0${sess}/anat -f sub-0${subj}_ses-0${sess}_T1w ${niidir}/sub-0${subj}/ses-0${sess}/anat
-    rm ${niidir}/sub-0${subj}/ses-0${sess}/anat/*/*.ima  # this may not work across subjects beyond #1 as the mp2 rage was received differently
+    # # convert to nii + BIDS and then remove the images that were extracted
+    # extract to the new sub folder that is at the source level give it the basic filename and 
+    ./dcm2niix -o ${niidir}sub-0${subj}/ses-0${sess}/anat -f sub-0${subj}_ses-0${sess}_T1w ${niidir}sub-0${subj}/ses-0${sess}/anat
+    rm ${niidir}sub-0${subj}/ses-0${sess}/anat/*/*.ima  # this may not work across subjects beyond #1 as the mp2 rage was received differently
     rm -r ${niidir}/sub-0${subj}/ses-0${sess}/anat/MP2RAGE_denoised/ 
+
 done
 done
 
@@ -92,19 +95,19 @@ for subj in "${subjs[@]}"; do
 
         for run in "${runs[@]}"; do
             
+            # get the filename for this run for finding
 			z=$(printf '*cmrr_att_learn_run0%d.zip' "${run}")
-            fname=$(find ${niidir}/sub-0${subj}_*/${z})
+            fname=$(find ${niidir}sub-0${subj}_*/${z})
             fname=$(printf ${fname})
             echo "print fname ${fname}"
             new_name=$(basename ${fname})
             new_name=$(echo $new_name | rev | cut -f 2- -d '.' | rev)
 
 			#echo "printing new name ${new_name}"
-            unzip "${fname}" -d "${niidir}/sub-0${subj}/ses-0${sess}/${new_name}"
-            ./dcm2niix -o ${niidir}/sub-0${subj}/ses-0${sess}/func -f sub-0${subj}_ses-0${sess}_%p ${niidir}/sub-0${subj}/ses-0${sess}/${new_name}
-
+            unzip "${fname}" -d "${niidir}sub-0${subj}/ses-0${sess}/${new_name}"
+            ./dcm2niix -o ${niidir}sub-0${subj}/ses-0${sess}/func -f sub-0${subj}_ses-0${sess}_%p ${niidir}sub-0${subj}/ses-0${sess}/${new_name}
             # remove the folder
-            rm -r ${niidir}/sub-0${subj}/ses-0${sess}/*_cmrr_att_learn_run*
+            rm -r ${niidir}sub-0${subj}/ses-0${sess}/*_cmrr_att_learn_run*
         done
     done
 done
@@ -122,27 +125,18 @@ for subj in "${subjs[@]}"; do
             new_name=$(basename $fname)
             new_name=$(echo $new_name | rev | cut -f 2- -d '.' | rev)
             echo "$new_name"
-            unzip ${fname} -d ${niidir}/sub-0${subj}/ses-0${sess}/func/${new_name} 
+            unzip ${fname} -d ${outpath}/sub-0${subj}/ses-0${sess}/func/${new_name} 
 #			./dcm2niix -o ${niidir}/sub-0${subj}/ses-0${sess}/func -f sub-0${subj}_ses-0${sess}_physiolog_%p ${niidir}/sub-0${subj}/ses-0${sess}/${new_name}
                 
         done
     done
 done
 
-# # # ####################################################################################################
-# # # #### Remove unneeded files ####
-# # # ####################################################################################################
+# # # # ####################################################################################################
+# # # # #### Remove unneeded files ####
+# # # # ####################################################################################################
 
 for subj in "${subjs[@]}"; do
 
     rm -rv ${niidir}/sub-0${subj}_*       
-done
-
-# # # ####################################################################################################
-# # # #### copy back to original location ####
-# # # ####################################################################################################
-for subj in "${subjs[@]}"; do
-
-    zip -r "${niidir}/sub-0${subj}.zip" "${niidir}/sub-0${subj}"
-    rsync -rv "${niidir}/sub-0${subj}.zip" "${rawloc}"
 done
